name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        repository: xtaci/kcptun
        ref: v20191105
    - uses: actions/setup-go@v1
    - name: go version
      run: go --version

